package view;

import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.CarrinhoTableModel;
import model.bean.Produtosbean;
import model.bean.Usuariobean;
import model.dao.carrinhoDAO;
import utils.Calculate;
import utils.InserirParametro;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author JOAOARTHURDELIMAFLOR
 */
public class TelaCarrinho extends javax.swing.JFrame {

    Usuariobean uBEAN;

    public String quantidade = "qtd";

    public CarrinhoTableModel carrinhoTableModel;
    public CarrinhoTableModel getValorTotal;
    public carrinhoDAO cDAO;

    public Double soma = 0.0;
    public TelaCarrinho telaCarrinho;

    public Double preco;
    TelaUsuarios telaUsuarios;

    Calculate calc = new Calculate();

    /**
     * Creates new form TelaCarrinho
     *
     * @throws java.io.FileNotFoundException
     */
    public TelaCarrinho() throws FileNotFoundException {
        initComponents();
        setIcon();

        cDAO = new carrinhoDAO();

        carrinhoTableModel = new CarrinhoTableModel(cDAO.read());
        jTabelaCarrinho.setModel(carrinhoTableModel);
        calc.calculaTotalProdutos(this, jTabelaCarrinho, lblPreçoTotal);

        //              ~~Espaçamento da Tabela Carrinho~~      
        jTabelaCarrinho.getColumnModel().getColumn(0).setPreferredWidth(90);
        jTabelaCarrinho.getColumnModel().getColumn(1).setPreferredWidth(90);
        jTabelaCarrinho.getColumnModel().getColumn(2).setPreferredWidth(40);
        jTabelaCarrinho.getColumnModel().getColumn(3).setPreferredWidth(90);
        jTabelaCarrinho.getColumnModel().getColumn(4).setPreferredWidth(5);
    }

    public void recebeProduto(String recebeProduto) throws FileNotFoundException {
        carrinhoTableModel.setDados(cDAO.readProduto(recebeProduto));
        TelaCarrinho carrinho = new TelaCarrinho();
        carrinho.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblLimparCarrinho = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabelaCarrinho = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblPreçoTotal = new javax.swing.JLabel();
        btnEnviarCarrinho = new javax.swing.JButton();
        btnImprimirCarrinho = new javax.swing.JButton();
        lblDescricao = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Catalogo Eletronico Uniun Juntas - Meu Carrinho");
        setBackground(new java.awt.Color(32, 56, 100));
        setMinimumSize(new java.awt.Dimension(400, 600));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(32, 56, 100)));

        jLabel12.setForeground(new java.awt.Color(32, 56, 100));
        jLabel12.setText("Copyright © 2020 – Shagas System & Uniun Juntas ");

        jPanel2.setBackground(new java.awt.Color(32, 56, 100));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logo.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cart2.png"))); // NOI18N
        jLabel2.setText("Carrinho");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        lblLimparCarrinho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/clear.png"))); // NOI18N
        lblLimparCarrinho.setToolTipText("Limpa o carrinho");
        lblLimparCarrinho.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblLimparCarrinho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLimparCarrinhoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblLimparCarrinho)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblLimparCarrinho)
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabelaCarrinho.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(32, 56, 100), 1, true));
        jTabelaCarrinho.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jTabelaCarrinho.setForeground(new java.awt.Color(32, 56, 100));
        jTabelaCarrinho.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Título 1"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTabelaCarrinho.setFillsViewportHeight(true);
        jTabelaCarrinho.setFocusCycleRoot(true);
        jTabelaCarrinho.setGridColor(new java.awt.Color(32, 56, 100));
        jTabelaCarrinho.setIntercellSpacing(new java.awt.Dimension(2, 2));
        jTabelaCarrinho.setName(""); // NOI18N
        jTabelaCarrinho.setRowHeight(30);
        jTabelaCarrinho.setSelectionBackground(new java.awt.Color(32, 56, 100));
        jTabelaCarrinho.setSelectionForeground(new java.awt.Color(255,255,255));
        jTabelaCarrinho.setShowVerticalLines(false);
        jTabelaCarrinho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabelaCarrinhoRemover(evt);
                jTabelaCarrinhoMudarQtd(evt);
                jTabelaCarrinhoVerAplicacao(evt);
            }
        });
        jTabelaCarrinho.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTabelaCarrinhoKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTabelaCarrinho);

        jPanel3.setBackground(new java.awt.Color(32, 56, 100));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Sub-Total | R$");

        lblPreçoTotal.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        lblPreçoTotal.setForeground(new java.awt.Color(255, 255, 255));
        lblPreçoTotal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblPreçoTotal.setText("0");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPreçoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPreçoTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        btnEnviarCarrinho.setBackground(new java.awt.Color(32, 56, 100));
        btnEnviarCarrinho.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnEnviarCarrinho.setForeground(new java.awt.Color(255, 255, 255));
        btnEnviarCarrinho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/@.png"))); // NOI18N
        btnEnviarCarrinho.setText("Enviar Cotação         ");
        btnEnviarCarrinho.setBorder(null);
        btnEnviarCarrinho.setBorderPainted(false);
        btnEnviarCarrinho.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnEnviarCarrinho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarCarrinhoActionPerformed(evt);
            }
        });

        btnImprimirCarrinho.setBackground(new java.awt.Color(32, 56, 100));
        btnImprimirCarrinho.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnImprimirCarrinho.setForeground(new java.awt.Color(255, 255, 255));
        btnImprimirCarrinho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/pdf.png"))); // NOI18N
        btnImprimirCarrinho.setText("Imprimir Carrinho      ");
        btnImprimirCarrinho.setBorder(null);
        btnImprimirCarrinho.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnImprimirCarrinho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirCarrinhoActionPerformed(evt);
            }
        });

        lblDescricao.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblDescricao.setForeground(new java.awt.Color(32, 56, 100));
        lblDescricao.setText("~~descrição~~");
        lblDescricao.setToolTipText("Clique em algum produto para ver sua descrição");

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(32, 56, 100));
        jLabel4.setText("Descrição");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel4)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDescricao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnImprimirCarrinho, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnEnviarCarrinho, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(0, 0, 0)
                .addComponent(lblDescricao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnImprimirCarrinho, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEnviarCarrinho, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTabelaCarrinhoRemover(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabelaCarrinhoRemover
        int selectedRow = jTabelaCarrinho.getSelectedRow();

        if (jTabelaCarrinho.getSelectedColumn() == 4) {
            int dialogResult = JOptionPane.showConfirmDialog(rootPane, "Tem certeza que deseja REMOVER " + lblDescricao.getText() + " do carrinho?", "", WIDTH);
            if (dialogResult == JOptionPane.YES_OPTION) {
                cDAO.delete(this, (int) jTabelaCarrinho.getModel().getValueAt(selectedRow, 0), (int) jTabelaCarrinho.getModel().getValueAt(selectedRow, 2));
                try {
                    calc.recalcula(jTabelaCarrinho, lblPreçoTotal);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(TelaCarrinho.class.getName()).log(Level.SEVERE, null, ex);
                }
                try {
                    carrinhoTableModel.setDados(cDAO.read());
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(TelaCarrinho.class.getName()).log(Level.SEVERE, null, ex);
                }
                try {
                    calc.calculaTotalProdutos(this, jTabelaCarrinho, lblPreçoTotal);
                } catch (FileNotFoundException ex1) {
                    Logger.getLogger(TelaCarrinho.class.getName()).log(Level.SEVERE, null, ex1);
                }
            }
        }
    }//GEN-LAST:event_jTabelaCarrinhoRemover

    private void jTabelaCarrinhoMudarQtd(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabelaCarrinhoMudarQtd
        int selectedRow = jTabelaCarrinho.getSelectedRow();

        if (jTabelaCarrinho.getSelectedColumn() == 2) {
            quantidade = JOptionPane.showInputDialog(this, "Insira uma quantidade");
            Produtosbean produto;
            produto = new Produtosbean();
            produto.setQtd(Integer.parseInt(quantidade));
            try {
                cDAO.update(produto, jTabelaCarrinho, (int) jTabelaCarrinho.getModel().getValueAt(selectedRow, 0), (int) jTabelaCarrinho.getModel().getValueAt(selectedRow, 2));
            } catch (FileNotFoundException ex) {
                Logger.getLogger(TelaCarrinho.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                carrinhoTableModel.setDados(cDAO.read());
            } catch (FileNotFoundException ex) {
                Logger.getLogger(TelaCarrinho.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                calc.recalcula(jTabelaCarrinho, lblPreçoTotal);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(TelaCarrinho.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                calc.calculaTotalProdutos(this, jTabelaCarrinho, lblPreçoTotal);
            } catch (FileNotFoundException ex1) {
                Logger.getLogger(TelaCarrinho.class.getName()).log(Level.SEVERE, null, ex1);
            }
        }
    }//GEN-LAST:event_jTabelaCarrinhoMudarQtd

    private void jTabelaCarrinhoVerAplicacao(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabelaCarrinhoVerAplicacao
        int selectedRow = jTabelaCarrinho.getSelectedRow();
        cDAO.readAplicacao((int) jTabelaCarrinho.getModel().getValueAt(selectedRow, 0), lblDescricao);
    }//GEN-LAST:event_jTabelaCarrinhoVerAplicacao

    private void btnImprimirCarrinhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirCarrinhoActionPerformed
        InserirParametro iS = new InserirParametro();
        iS.openJasper(this);
    }//GEN-LAST:event_btnImprimirCarrinhoActionPerformed

    private void btnEnviarCarrinhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarCarrinhoActionPerformed
        TelaEnviarEmail telaEmail = null;
        try {
            telaEmail = new TelaEnviarEmail();
            InserirParametro iS = new InserirParametro();
            iS.printPDF(this);
            telaEmail.setVisible(true);
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Erro ao abrir tela de envio de email. \n" + ex);
        }
    }//GEN-LAST:event_btnEnviarCarrinhoActionPerformed

    private void lblLimparCarrinhoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLimparCarrinhoMouseClicked
        int dialogResult = JOptionPane.showConfirmDialog(rootPane, "Tem certeza que deseja LIMPAR seu carrinho?", "", WIDTH);
        if (dialogResult == JOptionPane.YES_OPTION) {
            cDAO.clearCart();
            try {
                calc.recalcula(jTabelaCarrinho, lblPreçoTotal);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(TelaCarrinho.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                carrinhoTableModel.setDados(cDAO.read());
            } catch (FileNotFoundException ex) {
                Logger.getLogger(TelaCarrinho.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                calc.calculaTotalProdutos(this, jTabelaCarrinho, lblPreçoTotal);
            } catch (FileNotFoundException ex1) {
                Logger.getLogger(TelaCarrinho.class.getName()).log(Level.SEVERE, null, ex1);
            }
        }
    }//GEN-LAST:event_lblLimparCarrinhoMouseClicked

    private void jTabelaCarrinhoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTabelaCarrinhoKeyReleased
        int selectedRow = jTabelaCarrinho.getSelectedRow();
        if (evt.getKeyCode() == KeyEvent.VK_UP || evt.getKeyCode() == KeyEvent.VK_DOWN) {
            cDAO.readAplicacao((int) jTabelaCarrinho.getModel().getValueAt(selectedRow, 0), lblDescricao);
        }
    }//GEN-LAST:event_jTabelaCarrinhoKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCarrinho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCarrinho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCarrinho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCarrinho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new TelaCarrinho().setVisible(true);
                } catch (FileNotFoundException ex) {
                    System.out.println(ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviarCarrinho;
    private javax.swing.JButton btnImprimirCarrinho;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTabelaCarrinho;
    private javax.swing.JLabel lblDescricao;
    private javax.swing.JLabel lblLimparCarrinho;
    private javax.swing.JLabel lblPreçoTotal;
    // End of variables declaration//GEN-END:variables
    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icone.png")));
    }
}
