/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import model.AplicacaoTableModel;
import model.ProdutoTableModel2;
import model.bean.Aplicaçãobean;
import model.bean.Produtosbean;
import model.dao.aplicaçãoDAO;
import model.dao.produtoDAO;
import utils.ManipularImagem;

/**
 *
 * @author JOAOARTHURDELIMAFLOR
 */
public final class TelaGerProdutos extends javax.swing.JFrame {

    aplicaçãoDAO aDAO = new aplicaçãoDAO();
    AplicacaoTableModel aplicacaoTableModel = new AplicacaoTableModel(aDAO.read());

    produtoDAO pDAO = new produtoDAO();
    ProdutoTableModel2 produtoTableModel = new ProdutoTableModel2(pDAO.read(""));

    public BufferedImage imagem;

    /**
     * Creates new form TelaGerProdutos
     */
    public TelaGerProdutos() {
        initComponents();
        setIcon();
        tableModel();

//                          ~~PAINÉIS e BOTÕES~~
        paneAddAplicacao.setVisible(false);
        paneEditAplicacao.setVisible(false);
        paneEditProduto.setVisible(false);

        btnEditProduto.setEnabled(false);
        btnDelProd.setEnabled(false);
        btnAddAplic.setEnabled(false);
        btnEditAplic.setEnabled(false);
        btnDelAplic.setEnabled(false);
    }

    public void tableModel() {
        //                  ~~tablemodel (aplicação)~~
        jTabelaAplicação.setModel(aplicacaoTableModel);
        aplicacaoTableModel.clear();

        //                  ~~tablemodel (produtos)~~        
        pDAO = new produtoDAO();
        jTabelaProdutos.setModel(produtoTableModel);

        //              ~~Espaçamento da Tabela Aplicação~~      
        jTabelaAplicação.getColumnModel().getColumn(0).setPreferredWidth(50);
        jTabelaAplicação.getColumnModel().getColumn(1).setPreferredWidth(100);
        jTabelaAplicação.getColumnModel().getColumn(2).setPreferredWidth(30);
        jTabelaAplicação.getColumnModel().getColumn(3).setPreferredWidth(30);

        //              ~~Espaçamento da Tabela Produtos~~      
        jTabelaProdutos.getColumnModel().getColumn(0).setPreferredWidth(10);
        jTabelaProdutos.getColumnModel().getColumn(1).setPreferredWidth(40);
        jTabelaProdutos.getColumnModel().getColumn(2).setPreferredWidth(100);
        jTabelaProdutos.getColumnModel().getColumn(3).setPreferredWidth(200);
        jTabelaProdutos.getColumnModel().getColumn(4).setPreferredWidth(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTabelaProdutos = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane = new javax.swing.JScrollPane();
        jTabelaAplicação = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        btnEditProduto = new javax.swing.JButton();
        btnEditAplic = new javax.swing.JButton();
        btnAddAplic = new javax.swing.JButton();
        btnDelAplic = new javax.swing.JButton();
        btnDelProd = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lblImagem = new javax.swing.JLabel();
        paneEditProduto = new javax.swing.JPanel();
        txtEditPCodigo = new javax.swing.JTextField();
        txtEditPCodRef = new javax.swing.JTextField();
        btnTrocaImg = new javax.swing.JButton();
        txtEditPMontadora = new javax.swing.JTextField();
        txtEditPTipoPeca = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtEditPAplic = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtEditPPreco = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnEditPConfirm = new javax.swing.JButton();
        btnEditPClearFields = new javax.swing.JButton();
        paneEditAplicacao = new javax.swing.JPanel();
        txtEditACodigo = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtEditAMontadora = new javax.swing.JTextField();
        txtEditAAplicacao = new javax.swing.JTextField();
        txtEditAPistao = new javax.swing.JTextField();
        txtEditAMotor = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        btnEditAClearFields = new javax.swing.JButton();
        btnEditAConfirm = new javax.swing.JButton();
        paneAddAplicacao = new javax.swing.JPanel();
        txtAddACodigo = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtAddAMontadora = new javax.swing.JTextField();
        txtAddAAplicacao = new javax.swing.JTextField();
        txtAddAPistao = new javax.swing.JTextField();
        txtAddAMotor = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        btnAddAClearFields = new javax.swing.JButton();
        btnAddAConfirm = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gerenciamento de Produtos");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setForeground(new java.awt.Color(32, 56, 100));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 11, -1, 49));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logo2.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 11, -1, -1));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(32, 56, 100));
        jLabel2.setText("Gerenciamento dos Produtos");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 11, -1, 49));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jTabelaProdutos.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jTabelaProdutos.setForeground(new java.awt.Color(32, 56, 100));
        jTabelaProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Montadora", "Tipo de Peça", "Aplicação", "Preço"
            }
        ));
        jTabelaProdutos.setFillsViewportHeight(true);
        jTabelaProdutos.setGridColor(new java.awt.Color(32, 56, 100));
        jTabelaProdutos.setMaximumSize(new java.awt.Dimension(75, 750));
        jTabelaProdutos.setRowHeight(25);
        jTabelaProdutos.setRowMargin(3);
        jTabelaProdutos.setSelectionBackground(new java.awt.Color(32, 56, 100));
        jTabelaProdutos.setSelectionForeground(new java.awt.Color(255,255,255));
        jTabelaProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabelaProdutosMouseClicked(evt);
            }
        });
        jTabelaProdutos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTabelaProdutosKeyReleased(evt);
            }
        });
        jScrollPane3.setViewportView(jTabelaProdutos);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 642, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 71, -1, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jTabelaAplicação.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jTabelaAplicação.setForeground(new java.awt.Color(32, 56, 100));
        jTabelaAplicação.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Montadora", "Modelo", "Motor", "Pistão (Ø)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTabelaAplicação.setFillsViewportHeight(true);
        jTabelaAplicação.setGridColor(new java.awt.Color(32, 56, 100));
        jTabelaAplicação.setIntercellSpacing(new java.awt.Dimension(2, 3));
        jTabelaAplicação.setRowHeight(20);
        jTabelaAplicação.setSelectionBackground(new java.awt.Color(32, 56, 100));
        jTabelaAplicação.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabelaAplicaçãoMouseClicked(evt);
            }
        });
        jScrollPane.setViewportView(jTabelaAplicação);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(688, 71, -1, -1));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Preço cheio");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(605, 54, -1, -1));

        btnEditProduto.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnEditProduto.setText("Editar Produto");
        btnEditProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditProdutoActionPerformed(evt);
            }
        });
        jPanel1.add(btnEditProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(392, 220, -1, 37));

        btnEditAplic.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnEditAplic.setText("Editar Aplicação");
        btnEditAplic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditAplicActionPerformed(evt);
            }
        });
        jPanel1.add(btnEditAplic, new org.netbeans.lib.awtextra.AbsoluteConstraints(797, 220, -1, 37));

        btnAddAplic.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnAddAplic.setText("Adicionar Aplicação");
        btnAddAplic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAplicActionPerformed(evt);
            }
        });
        jPanel1.add(btnAddAplic, new org.netbeans.lib.awtextra.AbsoluteConstraints(652, 220, -1, 37));

        btnDelAplic.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnDelAplic.setText("Remover Aplicação");
        btnDelAplic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelAplicActionPerformed(evt);
            }
        });
        jPanel1.add(btnDelAplic, new org.netbeans.lib.awtextra.AbsoluteConstraints(924, 220, -1, 37));

        btnDelProd.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnDelProd.setText("Remover Produto");
        btnDelProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelProdActionPerformed(evt);
            }
        });
        jPanel1.add(btnDelProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(513, 219, -1, 39));

        lblImagem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImagem.setText("Imagem");
        lblImagem.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(32, 56, 100), 1, true));
        jScrollPane1.setViewportView(lblImagem);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 350, 340));

        paneEditProduto.setBackground(new java.awt.Color(255, 255, 255));
        paneEditProduto.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Edição de Produto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(32, 56, 100))); // NOI18N
        paneEditProduto.setLayout(null);

        txtEditPCodigo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        paneEditProduto.add(txtEditPCodigo);
        txtEditPCodigo.setBounds(6, 46, 165, 28);

        txtEditPCodRef.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        paneEditProduto.add(txtEditPCodRef);
        txtEditPCodRef.setBounds(189, 46, 272, 28);

        btnTrocaImg.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnTrocaImg.setText("Trocar Imagem");
        btnTrocaImg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrocaImgActionPerformed(evt);
            }
        });
        paneEditProduto.add(btnTrocaImg);
        btnTrocaImg.setBounds(479, 45, 172, 28);

        txtEditPMontadora.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        paneEditProduto.add(txtEditPMontadora);
        txtEditPMontadora.setBounds(6, 117, 202, 32);

        txtEditPTipoPeca.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        paneEditProduto.add(txtEditPTipoPeca);
        txtEditPTipoPeca.setBounds(226, 117, 202, 32);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Codigo Uniun");
        paneEditProduto.add(jLabel4);
        jLabel4.setBounds(6, 27, 72, 15);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Codigo Referencia (sperados por espaço)");
        paneEditProduto.add(jLabel5);
        jLabel5.setBounds(189, 27, 224, 15);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Montadora");
        paneEditProduto.add(jLabel6);
        jLabel6.setBounds(6, 96, 58, 15);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Tipo de Peça");
        paneEditProduto.add(jLabel7);
        jLabel7.setBounds(226, 96, 72, 15);

        txtEditPAplic.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        paneEditProduto.add(txtEditPAplic);
        txtEditPAplic.setBounds(6, 188, 422, 32);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Aplicação base (ex: 306/405/406 1.0 8v)");
        paneEditProduto.add(jLabel8);
        jLabel8.setBounds(6, 167, 226, 15);

        txtEditPPreco.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        paneEditProduto.add(txtEditPPreco);
        txtEditPPreco.setBounds(446, 188, 205, 32);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Preço cheio");
        paneEditProduto.add(jLabel9);
        jLabel9.setBounds(450, 170, 64, 20);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("(USAR PONTO)");
        paneEditProduto.add(jLabel10);
        jLabel10.setBounds(520, 170, 90, 20);

        btnEditPConfirm.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnEditPConfirm.setText("Confirmar Alterações");
        btnEditPConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditPConfirmActionPerformed(evt);
            }
        });
        paneEditProduto.add(btnEditPConfirm);
        btnEditPConfirm.setBounds(471, 251, 180, 28);

        btnEditPClearFields.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnEditPClearFields.setText("Limpar Campos");
        btnEditPClearFields.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditPClearFieldsActionPerformed(evt);
            }
        });
        paneEditProduto.add(btnEditPClearFields);
        btnEditPClearFields.setBounds(320, 250, 130, 28);

        jPanel1.add(paneEditProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(392, 264, 667, 297));

        paneEditAplicacao.setBackground(new java.awt.Color(255, 255, 255));
        paneEditAplicacao.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Edição de Aplicação", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(32, 56, 100))); // NOI18N

        txtEditACodigo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtEditACodigo.setEnabled(false);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Cdigo Uniun");

        txtEditAMontadora.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtEditAAplicacao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtEditAPistao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtEditAMotor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("Montadora");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("Aplicacao Individual (ex: 306)");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("Modelo do Motor");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("Diametro do Pistão (Ø)");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setText("(USAR PONTO)");

        btnEditAClearFields.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnEditAClearFields.setText("Limpar Campos");
        btnEditAClearFields.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditAClearFieldsActionPerformed(evt);
            }
        });

        btnEditAConfirm.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnEditAConfirm.setText("Confirmar Alterações");
        btnEditAConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditAConfirmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paneEditAplicacaoLayout = new javax.swing.GroupLayout(paneEditAplicacao);
        paneEditAplicacao.setLayout(paneEditAplicacaoLayout);
        paneEditAplicacaoLayout.setHorizontalGroup(
            paneEditAplicacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneEditAplicacaoLayout.createSequentialGroup()
                .addGroup(paneEditAplicacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEditACodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(paneEditAplicacaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneEditAplicacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneEditAplicacaoLayout.createSequentialGroup()
                        .addGroup(paneEditAplicacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEditAMontadora, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(paneEditAplicacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(txtEditAAplicacao, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(paneEditAplicacaoLayout.createSequentialGroup()
                        .addGroup(paneEditAplicacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEditAMotor, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addGap(18, 18, 18)
                        .addGroup(paneEditAplicacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(paneEditAplicacaoLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel16))
                            .addComponent(txtEditAPistao, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(80, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneEditAplicacaoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEditAClearFields)
                .addGap(18, 18, 18)
                .addComponent(btnEditAConfirm)
                .addContainerGap())
        );
        paneEditAplicacaoLayout.setVerticalGroup(
            paneEditAplicacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneEditAplicacaoLayout.createSequentialGroup()
                .addComponent(jLabel11)
                .addGap(7, 7, 7)
                .addComponent(txtEditACodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(paneEditAplicacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paneEditAplicacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEditAMontadora, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEditAAplicacao, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(paneEditAplicacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addGap(5, 5, 5)
                .addGroup(paneEditAplicacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEditAMotor, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEditAPistao, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(paneEditAplicacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEditAClearFields, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditAConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1.add(paneEditAplicacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 261, -1, -1));

        paneAddAplicacao.setBackground(new java.awt.Color(255, 255, 255));
        paneAddAplicacao.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Adicionar Aplicação", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(32, 56, 100))); // NOI18N

        txtAddACodigo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtAddACodigo.setEnabled(false);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setText("Cdigo Uniun");

        txtAddAMontadora.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtAddAAplicacao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtAddAPistao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtAddAMotor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel18.setText("Montadora");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel19.setText("Aplicacao Individual (ex: 306)");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel20.setText("Modelo do Motor");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel21.setText("Diametro do Pistão (Ø)");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel22.setText("(USAR PONTO)");

        btnAddAClearFields.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnAddAClearFields.setText("Limpar Campos");
        btnAddAClearFields.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAClearFieldsActionPerformed(evt);
            }
        });

        btnAddAConfirm.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnAddAConfirm.setText("Adicionar Aplicação");
        btnAddAConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAConfirmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paneAddAplicacaoLayout = new javax.swing.GroupLayout(paneAddAplicacao);
        paneAddAplicacao.setLayout(paneAddAplicacaoLayout);
        paneAddAplicacaoLayout.setHorizontalGroup(
            paneAddAplicacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneAddAplicacaoLayout.createSequentialGroup()
                .addGroup(paneAddAplicacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAddACodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(paneAddAplicacaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneAddAplicacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneAddAplicacaoLayout.createSequentialGroup()
                        .addGroup(paneAddAplicacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAddAMontadora, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addGap(18, 18, 18)
                        .addGroup(paneAddAplicacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(txtAddAAplicacao, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(paneAddAplicacaoLayout.createSequentialGroup()
                        .addGroup(paneAddAplicacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAddAMotor, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20))
                        .addGap(18, 18, 18)
                        .addGroup(paneAddAplicacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(paneAddAplicacaoLayout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel22))
                            .addComponent(txtAddAPistao, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(80, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneAddAplicacaoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAddAClearFields)
                .addGap(18, 18, 18)
                .addComponent(btnAddAConfirm)
                .addContainerGap())
        );
        paneAddAplicacaoLayout.setVerticalGroup(
            paneAddAplicacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneAddAplicacaoLayout.createSequentialGroup()
                .addComponent(jLabel17)
                .addGap(7, 7, 7)
                .addComponent(txtAddACodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(paneAddAplicacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paneAddAplicacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAddAMontadora, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAddAAplicacao, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(paneAddAplicacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22))
                .addGap(5, 5, 5)
                .addGroup(paneAddAplicacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAddAMotor, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAddAPistao, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(paneAddAplicacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAddAClearFields, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddAConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1.add(paneAddAplicacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 261, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTabelaProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabelaProdutosMouseClicked
        int selectedRow = jTabelaProdutos.getSelectedRow();

        //                                      ~~SET VISIBLE~~
        if (jTabelaProdutos.getSelectedRow() != -1) {
            btnEditProduto.setEnabled(true);
            btnDelProd.setEnabled(true);
            btnAddAplic.setEnabled(true);
            btnEditAplic.setEnabled(false);
            btnDelAplic.setEnabled(false);
        } else {
            btnEditProduto.setEnabled(false);
            btnDelProd.setEnabled(false);
            btnAddAplic.setEnabled(false);
        }
        if (selectedRow != - 1) {
            aplicacaoTableModel.setDados(aDAO.search((int) jTabelaProdutos.getModel().getValueAt(selectedRow, 0)));
            pDAO.readImage(jTabelaProdutos, lblImagem);
        }
    }//GEN-LAST:event_jTabelaProdutosMouseClicked

    private void jTabelaProdutosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTabelaProdutosKeyReleased
        int selectedRow = jTabelaProdutos.getSelectedRow();
        if (evt.getKeyCode() == KeyEvent.VK_UP || evt.getKeyCode() == KeyEvent.VK_DOWN) {
            aplicacaoTableModel.setDados(aDAO.search((int) jTabelaProdutos.getModel().getValueAt(selectedRow, 0)));
            pDAO.readImage(jTabelaProdutos, lblImagem);
        }
    }//GEN-LAST:event_jTabelaProdutosKeyReleased

    private void btnEditProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditProdutoActionPerformed
        paneAddAplicacao.setVisible(false);
        paneEditAplicacao.setVisible(false);
        paneEditProduto.setVisible(true);

        if (jTabelaProdutos.getSelectedRow() != -1) {
            pDAO.read2(jTabelaProdutos, lblImagem, txtEditPCodRef, txtEditPCodigo, txtEditPMontadora, txtEditPTipoPeca, txtEditPAplic, txtEditPPreco);
        }
    }//GEN-LAST:event_btnEditProdutoActionPerformed

    private void btnAddAplicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAplicActionPerformed
        int selectedRow = jTabelaProdutos.getSelectedRow();
        paneAddAplicacao.setVisible(true);
        paneEditAplicacao.setVisible(false);
        paneEditProduto.setVisible(false);

//                      ~~GET DADOS~~
        if (jTabelaProdutos.getSelectedRow() != -1) {
            try {
                pDAO.readCod2((int) jTabelaProdutos.getValueAt(selectedRow, 0), txtAddACodigo);
            } catch (SQLException ex) {
                Logger.getLogger(TelaGerProdutos.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnAddAplicActionPerformed

    private void btnEditAplicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditAplicActionPerformed
        int selectedRow = jTabelaProdutos.getSelectedRow();
        paneAddAplicacao.setVisible(false);
        paneEditAplicacao.setVisible(true);
        paneEditProduto.setVisible(false);

//                      ~~GET DADOS~~
        if (jTabelaAplicação.getSelectedRow() != -1) {
            aDAO.read2(jTabelaProdutos, txtEditACodigo, txtEditAMontadora, txtEditAMotor, txtEditAMotor, txtEditAPistao);
            txtEditACodigo.setText(jTabelaProdutos.getValueAt(selectedRow, 0).toString());
        }
    }//GEN-LAST:event_btnEditAplicActionPerformed

    private void jTabelaAplicaçãoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabelaAplicaçãoMouseClicked
//                      ~~SET VISIBLE~~
        if (jTabelaAplicação.getSelectedRow() != -1) {
            btnEditAplic.setEnabled(true);
            btnDelAplic.setEnabled(true);
            btnEditProduto.setEnabled(false);
            btnDelProd.setEnabled(false);
            btnAddAplic.setEnabled(false);
        } else {
            btnEditAplic.setEnabled(false);
            btnDelAplic.setEnabled(false);
        }
    }//GEN-LAST:event_jTabelaAplicaçãoMouseClicked

    private void btnAddAConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAConfirmActionPerformed
        Aplicaçãobean aplicacao;
        aplicacao = new Aplicaçãobean();
        aplicaçãoDAO adao = new aplicaçãoDAO();

        if (txtAddACodigo.getText().equals("")
                || txtAddAMontadora.getText().equals("")
                || txtAddAAplicacao.getText().equals("")
                || txtAddAMotor.getText().equals("")
                || txtAddAPistao.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Complete todos os campos para cadastrar");
        } else {
            aplicacao.setCodigo(Integer.parseInt(txtAddACodigo.getText()));
            aplicacao.setMontadora(txtAddAMontadora.getText());
            aplicacao.setModelo(txtAddAAplicacao.getText());
            aplicacao.setMotor(txtAddAMotor.getText());
            aplicacao.setPistao(Double.parseDouble(txtAddAPistao.getText()));

            adao.create(aplicacao);
            JOptionPane.showMessageDialog(rootPane, "Aplicação cadastrada com sucesso!");
            aplicacaoTableModel.setDados(aDAO.read());
        }
    }//GEN-LAST:event_btnAddAConfirmActionPerformed

    private void btnAddAClearFieldsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAClearFieldsActionPerformed
        txtAddAAplicacao.setText("");
        txtAddAMontadora.setText("");
        txtAddAMotor.setText("");
        txtAddAPistao.setText("");
    }//GEN-LAST:event_btnAddAClearFieldsActionPerformed

    private void btnTrocaImgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrocaImgActionPerformed
        JFileChooser fc = new JFileChooser();
        int res = fc.showOpenDialog(null);

        if (res == JFileChooser.APPROVE_OPTION) {
            File arquivo = fc.getSelectedFile();
            try {
                imagem = ManipularImagem.setImagemDimensao(arquivo.getAbsolutePath(), 1280, 720);

                lblImagem.setIcon(new ImageIcon(imagem));
                lblImagem.setText("");

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(rootPane, "Erro ao obter imagem! \n" + ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecione uma imagem");
        }
    }//GEN-LAST:event_btnTrocaImgActionPerformed

    private void btnEditPConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditPConfirmActionPerformed
        int selectedRow = jTabelaProdutos.getSelectedRow();
        try {
            Produtosbean produto;
            produto = new Produtosbean();
            produtoDAO pdao = new produtoDAO();

            produto.setImagem(ManipularImagem.getImgBytes(imagem));
            produto.setCodigoref(txtEditPCodRef.getText());
            produto.setCodigo(Integer.parseInt(txtEditPCodigo.getText()));
            produto.setMontadora(txtEditPMontadora.getText());
            produto.setTipopeca(txtEditPTipoPeca.getText());
            produto.setAplicacao(txtEditPAplic.getText());
            produto.setPreco(Double.parseDouble(txtEditPPreco.getText()));

            pdao.update(produto, jTabelaProdutos.getValueAt(selectedRow, 0).toString());
            produtoTableModel.setDados(pDAO.read(""));
            System.out.println(produto);
            
            JOptionPane.showMessageDialog(rootPane, "Produto alterado com sucesso");
        } catch (NullPointerException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao atualizar o produto \n" + ex);
        }
    }//GEN-LAST:event_btnEditPConfirmActionPerformed

    private void btnEditPClearFieldsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditPClearFieldsActionPerformed
        txtEditPAplic.setText("");
        txtEditPCodRef.setText("");
        txtEditPCodigo.setText("");
        txtEditPMontadora.setText("");
        txtEditPPreco.setText("");
        txtEditPTipoPeca.setText("");
        lblImagem.setIcon(null);
        lblImagem.setText("Imagem");
    }//GEN-LAST:event_btnEditPClearFieldsActionPerformed

    private void btnEditAClearFieldsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditAClearFieldsActionPerformed
        txtEditAMontadora.setText("");
        txtEditAAplicacao.setText("");
        txtEditAPistao.setText("");
        txtEditAMotor.setText("");
    }//GEN-LAST:event_btnEditAClearFieldsActionPerformed

    private void btnEditAConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditAConfirmActionPerformed
        aDAO.update(null, jTabelaAplicação, this, txtAddAAplicacao, txtEditAAplicacao, txtEditAMotor, txtEditAPistao);
    }//GEN-LAST:event_btnEditAConfirmActionPerformed

    private void btnDelProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelProdActionPerformed
        int selectedRow = jTabelaProdutos.getSelectedRow();

        int dialogResult = JOptionPane.showConfirmDialog(rootPane, "Tem certeza que deseja REMOVER " + jTabelaProdutos.getValueAt(selectedRow, 3) + "?", "", WIDTH);
        if (dialogResult == JOptionPane.YES_OPTION) {
            pDAO.delete((int) jTabelaProdutos.getValueAt(selectedRow, 0));
            JOptionPane.showMessageDialog(rootPane, "Produto " + jTabelaProdutos.getValueAt(selectedRow, 3) + " \n deletado com sucesso");
            produtoTableModel.setDados(pDAO.read(""));
            lblImagem.setIcon(null);
            lblImagem.setText("Imagem");
        }
    }//GEN-LAST:event_btnDelProdActionPerformed

    private void btnDelAplicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelAplicActionPerformed
        int selectedRow = jTabelaAplicação.getSelectedRow();

        int dialogResult = JOptionPane.showConfirmDialog(rootPane, "Tem certeza que deseja REMOVER " + jTabelaAplicação.getValueAt(selectedRow, 1) + "?", "", WIDTH);
        if (dialogResult == JOptionPane.YES_OPTION) {
            aDAO.delete(jTabelaAplicação);
            JOptionPane.showMessageDialog(rootPane, "Aplicação de " + jTabelaProdutos.getValueAt(selectedRow, 3) + " \n deletado com sucesso");
            aplicacaoTableModel.setDados(aDAO.read());
            lblImagem.setIcon(null);
            lblImagem.setText("Imagem");
        }
    }//GEN-LAST:event_btnDelAplicActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaGerProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TelaGerProdutos().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddAClearFields;
    private javax.swing.JButton btnAddAConfirm;
    private javax.swing.JButton btnAddAplic;
    private javax.swing.JButton btnDelAplic;
    private javax.swing.JButton btnDelProd;
    private javax.swing.JButton btnEditAClearFields;
    private javax.swing.JButton btnEditAConfirm;
    private javax.swing.JButton btnEditAplic;
    private javax.swing.JButton btnEditPClearFields;
    private javax.swing.JButton btnEditPConfirm;
    private javax.swing.JButton btnEditProduto;
    private javax.swing.JButton btnTrocaImg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTabelaAplicação;
    private javax.swing.JTable jTabelaProdutos;
    private javax.swing.JLabel lblImagem;
    private javax.swing.JPanel paneAddAplicacao;
    private javax.swing.JPanel paneEditAplicacao;
    private javax.swing.JPanel paneEditProduto;
    private javax.swing.JTextField txtAddAAplicacao;
    private javax.swing.JTextField txtAddACodigo;
    private javax.swing.JTextField txtAddAMontadora;
    private javax.swing.JTextField txtAddAMotor;
    private javax.swing.JTextField txtAddAPistao;
    private javax.swing.JTextField txtEditAAplicacao;
    private javax.swing.JTextField txtEditACodigo;
    private javax.swing.JTextField txtEditAMontadora;
    private javax.swing.JTextField txtEditAMotor;
    private javax.swing.JTextField txtEditAPistao;
    private javax.swing.JTextField txtEditPAplic;
    private javax.swing.JTextField txtEditPCodRef;
    private javax.swing.JTextField txtEditPCodigo;
    private javax.swing.JTextField txtEditPMontadora;
    private javax.swing.JTextField txtEditPPreco;
    private javax.swing.JTextField txtEditPTipoPeca;
    // End of variables declaration//GEN-END:variables
    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icone.png")));
    }
}