package view;

import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.io.FileNotFoundException;
import model.ProdutoTableModel;
import javax.swing.UnsupportedLookAndFeelException;
import model.AplicacaoTableModel;
import model.dao.aplicaçãoDAO;
import model.dao.produtoDAO;
import java.sql.SQLException;
import model.bean.Produtosbean;
import javax.swing.JOptionPane;
import model.CarrinhoTableModel;
import model.dao.carrinhoDAO;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author JOAOARTHURDELIMAFLORES
 */
public final class TelaProdutos extends javax.swing.JFrame {

    aplicaçãoDAO aDAO = new aplicaçãoDAO();
    AplicacaoTableModel aplicacaoTableModel = new AplicacaoTableModel(aDAO.read());

    produtoDAO pDAO = new produtoDAO();
    ProdutoTableModel produtoTableModel = new ProdutoTableModel(pDAO.read(""));
    
    public CarrinhoTableModel carrinhoTableModel;
    public carrinhoDAO cDAO;

    public String quantidade = "qtd";

//              ~~ENVIA PRODUTOS PRO CARRINHO~~
    TelaCarrinho enviarProduto;    

    public TelaProdutos() throws SQLException {
        initComponents();
        setIcon();
        tableModel();
        
        lblFecharPesquisaAvançada.setVisible(false);
        panePesquisaAvançada.setVisible(false);
    }
    
    public void tableModel () {
        //              ~~tablemodel (aplicação)~~           
        jTabelaAplicação.setModel(aplicacaoTableModel);
        aplicacaoTableModel.clear();

        //                  ~~tablemodel (produtos)~~        
        jTabelaProdutos.setModel(produtoTableModel);

        //              ~~Espaçamento da Tabela Aplicação~~      
        jTabelaAplicação.getColumnModel().getColumn(0).setPreferredWidth(50);
        jTabelaAplicação.getColumnModel().getColumn(1).setPreferredWidth(200);
        jTabelaAplicação.getColumnModel().getColumn(2).setPreferredWidth(50);
        jTabelaAplicação.getColumnModel().getColumn(3).setPreferredWidth(30);

        //              ~~Espaçamento da Tabela Produtos~~      
        jTabelaProdutos.getColumnModel().getColumn(0).setPreferredWidth(10);
        jTabelaProdutos.getColumnModel().getColumn(1).setPreferredWidth(40);
        jTabelaProdutos.getColumnModel().getColumn(2).setPreferredWidth(120);
        jTabelaProdutos.getColumnModel().getColumn(3).setPreferredWidth(300);
        jTabelaProdutos.getColumnModel().getColumn(4).setPreferredWidth(0);        
    }

    public void recebePesquisaGeral(String recebePG) {
        produtoTableModel.setDados(pDAO.read(recebePG));
    }

    public void recebeCodigo(String recebeCod) {
        produtoTableModel.setDados(pDAO.readCod(recebeCod));
    }

    public void recebeMontadora(String recebeM) {
        produtoTableModel.setDados(pDAO.readMontadora(recebeM));
    }

    public void recebeTipo(String recebeTipo) {
        produtoTableModel.setDados(pDAO.readTipopeca(recebeTipo));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lbl_dispose = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblHome = new javax.swing.JLabel();
        txtGambiarra = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtPesquisaGeral = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        lblPesquisaGeral = new javax.swing.JLabel();
        lblPesquisaAvançada = new javax.swing.JLabel();
        lblFecharPesquisaAvançada = new javax.swing.JLabel();
        lblAbrirPesquisaAvançada = new javax.swing.JLabel();
        btnCarinho = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabelaProdutos = new javax.swing.JTable();
        paneLateral = new javax.swing.JPanel();
        btnAddCarinho = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane = new javax.swing.JScrollPane();
        jTabelaAplicação = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        lblImagem = new javax.swing.JLabel();
        panePesquisaAvançada = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        lblPesquisaCod = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        lblPesquisaAplicacao = new javax.swing.JLabel();
        txtAplicacao = new javax.swing.JTextField();
        lblTipoPeca = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblPesquisaMontadora = new javax.swing.JLabel();
        txtMontadora = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        txtTipopeca = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        txtMotor = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        lblPesquisaMotor = new javax.swing.JLabel();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Catalogo Eletronico Uniun Juntas - Catalogo");
        setMaximumSize(new java.awt.Dimension(1274, 727));
        setMinimumSize(new java.awt.Dimension(1274, 727));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(32, 56, 100)));

        jPanel2.setBackground(new java.awt.Color(32, 56, 100));

        lbl_dispose.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        lbl_dispose.setForeground(new java.awt.Color(255, 255, 255));
        lbl_dispose.setText("X");
        lbl_dispose.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lbl_dispose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_disposeMouseClicked(evt);
            }
        });

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logo.png"))); // NOI18N
        lblLogo.setToolTipText("Voltar ao início");
        lblLogo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHomeMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Catalogo Eletronico");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        lblHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/home.png"))); // NOI18N
        lblHome.setToolTipText("Voltar ao início");
        lblHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHomeMouseClicked(evt);
            }
        });

        txtGambiarra.setBackground(new java.awt.Color(32, 56, 100));
        txtGambiarra.setForeground(new java.awt.Color(32, 56, 100));
        txtGambiarra.setText("jTextField1");
        txtGambiarra.setBorder(null);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHome, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(lblLogo)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtGambiarra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_dispose)
                .addGap(21, 21, 21))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtGambiarra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jSeparator1)
                            .addComponent(lbl_dispose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );

        jLabel14.setForeground(new java.awt.Color(32, 56, 100));
        jLabel14.setText("Copyright © 2020 – Shagas System & Uniun Juntas ");

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(32, 56, 100));
        jLabel3.setText("Pesquisa Geral");

        txtPesquisaGeral.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtPesquisaGeral.setForeground(new java.awt.Color(153, 153, 153));
        txtPesquisaGeral.setText("Pesquisa Geral (código, montadora, etc)");
        txtPesquisaGeral.setBorder(null);
        txtPesquisaGeral.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPesquisaGeralFocusGained(evt);
                txtPesquisaGeralFocusGained2(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPesquisaGeralFocusLost(evt);
            }
        });
        txtPesquisaGeral.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPesquisaGeralKeyPressed(evt);
            }
        });

        lblPesquisaGeral.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/lupa.png"))); // NOI18N
        lblPesquisaGeral.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblPesquisaGeral.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPesquisaGeralMouseClicked(evt);
            }
        });

        lblPesquisaAvançada.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        lblPesquisaAvançada.setForeground(new java.awt.Color(32, 56, 100));
        lblPesquisaAvançada.setText("Pesquisa Avançada");
        lblPesquisaAvançada.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblPesquisaAvançada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPesquisaAvançadaMouseClicked(evt);
            }
        });

        lblFecharPesquisaAvançada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/arrow_up.png"))); // NOI18N
        lblFecharPesquisaAvançada.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblFecharPesquisaAvançada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFecharPesquisaAvançadaMouseClicked(evt);
            }
        });

        lblAbrirPesquisaAvançada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/arrow_down.png"))); // NOI18N
        lblAbrirPesquisaAvançada.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblAbrirPesquisaAvançada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAbrirPesquisaAvançadaMouseClicked(evt);
            }
        });

        btnCarinho.setBackground(new java.awt.Color(32, 56, 100));
        btnCarinho.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnCarinho.setForeground(new java.awt.Color(255, 255, 255));
        btnCarinho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cart2.png"))); // NOI18N
        btnCarinho.setText("    Carrinho       ");
        btnCarinho.setBorder(null);
        btnCarinho.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCarinho.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnCarinho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarinhoActionPerformed(evt);
            }
        });

        jTabelaProdutos.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jTabelaProdutos.setForeground(new java.awt.Color(32, 56, 100));
        jTabelaProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Montadora", "Tipo de Peça", "Aplicação", "Preço"
            }
        ));
        jTabelaProdutos.setGridColor(new java.awt.Color(32, 56, 100));
        jTabelaProdutos.setMaximumSize(new java.awt.Dimension(75, 750));
        jTabelaProdutos.setRowHeight(25);
        jTabelaProdutos.setRowMargin(3);
        jTabelaProdutos.setSelectionBackground(new java.awt.Color(32, 56, 100));
        jTabelaProdutos.setSelectionForeground(new java.awt.Color(255,255,255));
        jTabelaProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabelaProdutosMouseClicked(evt);
            }
        });
        jTabelaProdutos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTabelaProdutosKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTabelaProdutos);
        if (jTabelaProdutos.getColumnModel().getColumnCount() > 0) {
            jTabelaProdutos.getColumnModel().getColumn(0).setResizable(false);
            jTabelaProdutos.getColumnModel().getColumn(1).setResizable(false);
            jTabelaProdutos.getColumnModel().getColumn(2).setResizable(false);
            jTabelaProdutos.getColumnModel().getColumn(3).setResizable(false);
            jTabelaProdutos.getColumnModel().getColumn(4).setResizable(false);
        }

        paneLateral.setBackground(new java.awt.Color(255, 255, 255));

        btnAddCarinho.setBackground(new java.awt.Color(32, 56, 100));
        btnAddCarinho.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnAddCarinho.setForeground(new java.awt.Color(255, 255, 255));
        btnAddCarinho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cart2.png"))); // NOI18N
        btnAddCarinho.setText("    Adicionar ao Carrinho");
        btnAddCarinho.setBorder(null);
        btnAddCarinho.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAddCarinho.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnAddCarinho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCarinhoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(32, 56, 100));
        jLabel1.setText("Aplicação");

        jTabelaAplicação.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jTabelaAplicação.setForeground(new java.awt.Color(32, 56, 100));
        jTabelaAplicação.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Montadora", "Modelo", "Motor", "Pistão (Ø)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTabelaAplicação.setFillsViewportHeight(true);
        jTabelaAplicação.setGridColor(new java.awt.Color(32, 56, 100));
        jTabelaAplicação.setIntercellSpacing(new java.awt.Dimension(2, 3));
        jTabelaAplicação.setRowHeight(20);
        jTabelaAplicação.setSelectionBackground(new java.awt.Color(32, 56, 100));
        jTabelaAplicação.setSelectionForeground(getBackground());
        jScrollPane.setViewportView(jTabelaAplicação);

        lblImagem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImagem.setText("Imagem");
        jScrollPane3.setViewportView(lblImagem);

        javax.swing.GroupLayout paneLateralLayout = new javax.swing.GroupLayout(paneLateral);
        paneLateral.setLayout(paneLateralLayout);
        paneLateralLayout.setHorizontalGroup(
            paneLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneLateralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(380, Short.MAX_VALUE))
            .addComponent(jScrollPane)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneLateralLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnAddCarinho))
            .addComponent(jScrollPane3)
        );
        paneLateralLayout.setVerticalGroup(
            paneLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneLateralLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAddCarinho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(32, 56, 100));
        jLabel6.setText("Código");

        txtCodigo.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtCodigo.setText("Código Uniun ou referência");
        txtCodigo.setBorder(null);
        txtCodigo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCodigoFocusGained(evt);
                txtCodigoFocusGained2(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCodigoFocusLost(evt);
            }
        });
        txtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCodigoKeyPressed(evt);
            }
        });

        lblPesquisaCod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/lupa.png"))); // NOI18N
        lblPesquisaCod.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblPesquisaCod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPesquisaCodMouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(32, 56, 100));
        jLabel8.setText("Aplicação");

        lblPesquisaAplicacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/lupa.png"))); // NOI18N
        lblPesquisaAplicacao.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblPesquisaAplicacao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPesquisaAplicacaoMouseClicked(evt);
            }
        });

        txtAplicacao.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtAplicacao.setBorder(null);
        txtAplicacao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAplicacaoKeyPressed(evt);
            }
        });

        lblTipoPeca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/lupa.png"))); // NOI18N
        lblTipoPeca.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblTipoPeca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTipoPecaMouseClicked(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(32, 56, 100));
        jLabel11.setText("Tipo de Peça");

        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(32, 56, 100));
        jLabel12.setText("Montadora");

        lblPesquisaMontadora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/lupa.png"))); // NOI18N
        lblPesquisaMontadora.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblPesquisaMontadora.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPesquisaMontadoraMouseClicked(evt);
            }
        });

        txtMontadora.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtMontadora.setBorder(null);
        txtMontadora.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMontadoraKeyPressed(evt);
            }
        });

        txtTipopeca.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtTipopeca.setBorder(null);
        txtTipopeca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTipopecaKeyPressed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(32, 56, 100));
        jLabel13.setText("Motor");

        txtMotor.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtMotor.setBorder(null);
        txtMotor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMotorKeyPressed(evt);
            }
        });

        lblPesquisaMotor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/lupa.png"))); // NOI18N
        lblPesquisaMotor.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblPesquisaMotor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPesquisaMotorMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panePesquisaAvançadaLayout = new javax.swing.GroupLayout(panePesquisaAvançada);
        panePesquisaAvançada.setLayout(panePesquisaAvançadaLayout);
        panePesquisaAvançadaLayout.setHorizontalGroup(
            panePesquisaAvançadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panePesquisaAvançadaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panePesquisaAvançadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panePesquisaAvançadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panePesquisaAvançadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                        .addComponent(jSeparator3))
                    .addGroup(panePesquisaAvançadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtMontadora)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panePesquisaAvançadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPesquisaMontadora)
                    .addComponent(lblPesquisaCod))
                .addGap(18, 18, 18)
                .addGroup(panePesquisaAvançadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panePesquisaAvançadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panePesquisaAvançadaLayout.createSequentialGroup()
                        .addGroup(panePesquisaAvançadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTipopeca, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
                            .addComponent(jSeparator6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTipoPeca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panePesquisaAvançadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMotor)
                            .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPesquisaMotor))
                    .addGroup(panePesquisaAvançadaLayout.createSequentialGroup()
                        .addGroup(panePesquisaAvançadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtAplicacao, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE)
                            .addComponent(jSeparator4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPesquisaAplicacao)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panePesquisaAvançadaLayout.setVerticalGroup(
            panePesquisaAvançadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panePesquisaAvançadaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panePesquisaAvançadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panePesquisaAvançadaLayout.createSequentialGroup()
                        .addGroup(panePesquisaAvançadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPesquisaAplicacao)
                            .addGroup(panePesquisaAvançadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtAplicacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8)))
                        .addGap(0, 0, 0)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panePesquisaAvançadaLayout.createSequentialGroup()
                        .addGroup(panePesquisaAvançadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panePesquisaAvançadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblPesquisaCod))
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panePesquisaAvançadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(lblPesquisaMontadora)
                    .addGroup(panePesquisaAvançadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel13))
                    .addGroup(panePesquisaAvançadaLayout.createSequentialGroup()
                        .addComponent(txtMontadora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panePesquisaAvançadaLayout.createSequentialGroup()
                        .addGroup(panePesquisaAvançadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTipopeca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTipoPeca))
                        .addGap(0, 0, 0)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblPesquisaMotor)
                    .addGroup(panePesquisaAvançadaLayout.createSequentialGroup()
                        .addComponent(txtMotor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(15, 15, 15)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPesquisaGeral, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblPesquisaGeral)
                                .addGap(56, 56, 56)
                                .addComponent(lblPesquisaAvançada)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblAbrirPesquisaAvançada)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblFecharPesquisaAvançada)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCarinho, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 744, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(paneLateral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(panePesquisaAvançada, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel14)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtPesquisaGeral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPesquisaGeral, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPesquisaAvançada)
                            .addComponent(lblFecharPesquisaAvançada, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAbrirPesquisaAvançada, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCarinho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panePesquisaAvançada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(paneLateral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_disposeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_disposeMouseClicked
        this.dispose();
    }//GEN-LAST:event_lbl_disposeMouseClicked

    private void txtPesquisaGeralFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPesquisaGeralFocusGained
        if (txtPesquisaGeral.getText().isEmpty()) {
            txtPesquisaGeral.setText("Pesquisa Geral (código, montadora, etc)");
        }
    }//GEN-LAST:event_txtPesquisaGeralFocusGained

    private void txtPesquisaGeralFocusGained2(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPesquisaGeralFocusGained2
        if (txtPesquisaGeral.getText().equals("Pesquisa Geral (código, montadora, etc)")) {
            txtPesquisaGeral.setText("");
        }
    }//GEN-LAST:event_txtPesquisaGeralFocusGained2

    private void txtPesquisaGeralFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPesquisaGeralFocusLost
        if (txtPesquisaGeral.getText().equals("")) {
            txtPesquisaGeral.setText("Pesquisa Geral (código, montadora, etc)");
        }
    }//GEN-LAST:event_txtPesquisaGeralFocusLost

    private void lblHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeMouseClicked
        try {
            new TelaPesquisa().setVisible(true);
            this.dispose();
        } catch (UnsupportedLookAndFeelException ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_lblHomeMouseClicked

    private void lblAbrirPesquisaAvançadaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAbrirPesquisaAvançadaMouseClicked
        panePesquisaAvançada.setVisible(true);
        lblAbrirPesquisaAvançada.setVisible(false);
        lblFecharPesquisaAvançada.setVisible(true);
    }//GEN-LAST:event_lblAbrirPesquisaAvançadaMouseClicked

    private void lblFecharPesquisaAvançadaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFecharPesquisaAvançadaMouseClicked
        panePesquisaAvançada.setVisible(false);
        lblAbrirPesquisaAvançada.setVisible(true);
        lblFecharPesquisaAvançada.setVisible(false);
    }//GEN-LAST:event_lblFecharPesquisaAvançadaMouseClicked

    private void lblPesquisaAvançadaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPesquisaAvançadaMouseClicked
        if (lblAbrirPesquisaAvançada.isVisible()) {
            lblAbrirPesquisaAvançadaMouseClicked(evt);
        } else {
            lblFecharPesquisaAvançadaMouseClicked(evt);
        }
    }//GEN-LAST:event_lblPesquisaAvançadaMouseClicked

    private void jTabelaProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabelaProdutosMouseClicked
        int selectedRow = jTabelaProdutos.getSelectedRow();        
        pDAO.readImage(jTabelaProdutos, lblImagem);
        aplicacaoTableModel.setDados(aDAO.search((int) jTabelaProdutos.getModel().getValueAt(selectedRow, 0)));
    }//GEN-LAST:event_jTabelaProdutosMouseClicked

    private void lblPesquisaGeralMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPesquisaGeralMouseClicked
        produtoTableModel.setDados(pDAO.read(txtPesquisaGeral.getText()));
        aplicacaoTableModel.clear();
        lblImagem.setIcon(null);
        lblImagem.setText("Imagem");
    }//GEN-LAST:event_lblPesquisaGeralMouseClicked

    private void txtPesquisaGeralKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisaGeralKeyPressed
        if (KeyEvent.VK_ENTER == evt.getKeyCode()) {
            produtoTableModel.setDados(pDAO.read(txtPesquisaGeral.getText()));
            aplicacaoTableModel.clear();
            lblImagem.setIcon(null);
            lblImagem.setText("Imagem");
        }
    }//GEN-LAST:event_txtPesquisaGeralKeyPressed

    private void lblPesquisaCodMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPesquisaCodMouseClicked
        produtoTableModel.setDados(pDAO.readCod(txtCodigo.getText()));
        aplicacaoTableModel.clear();
    }//GEN-LAST:event_lblPesquisaCodMouseClicked

    private void txtCodigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoKeyPressed
        if (KeyEvent.VK_ENTER == evt.getKeyCode()) {
            produtoTableModel.setDados(pDAO.readCod(txtCodigo.getText()));
            aplicacaoTableModel.clear();
            lblImagem.setIcon(null);
            lblImagem.setText("Imagem");
        }
    }//GEN-LAST:event_txtCodigoKeyPressed

    private void txtMontadoraKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMontadoraKeyPressed
        if (KeyEvent.VK_ENTER == evt.getKeyCode()) {
            produtoTableModel.setDados(pDAO.readMontadora(txtMontadora.getText()));
            aplicacaoTableModel.clear();
            lblImagem.setIcon(null);
            lblImagem.setText("Imagem");
        }
    }//GEN-LAST:event_txtMontadoraKeyPressed

    private void txtTipopecaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTipopecaKeyPressed
        if (KeyEvent.VK_ENTER == evt.getKeyCode()) {
            produtoTableModel.setDados(pDAO.readTipopeca(txtTipopeca.getText()));
            aplicacaoTableModel.clear();
        }
    }//GEN-LAST:event_txtTipopecaKeyPressed

    private void txtAplicacaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAplicacaoKeyPressed
        if (KeyEvent.VK_ENTER == evt.getKeyCode()) {
            produtoTableModel.setDados(pDAO.readAplicacao(txtAplicacao.getText()));
            aplicacaoTableModel.clear();
            lblImagem.setIcon(null);
            lblImagem.setText("Imagem");
        }
    }//GEN-LAST:event_txtAplicacaoKeyPressed

    private void lblPesquisaAplicacaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPesquisaAplicacaoMouseClicked
        produtoTableModel.setDados(pDAO.readAplicacao(txtAplicacao.getText()));
        aplicacaoTableModel.clear();
        lblImagem.setIcon(null);
        lblImagem.setText("Imagem");
    }//GEN-LAST:event_lblPesquisaAplicacaoMouseClicked

    private void lblTipoPecaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTipoPecaMouseClicked
        produtoTableModel.setDados(pDAO.readTipopeca(txtTipopeca.getText()));
        aplicacaoTableModel.clear();
        lblImagem.setIcon(null);
        lblImagem.setText("Imagem");
    }//GEN-LAST:event_lblTipoPecaMouseClicked

    private void lblPesquisaMontadoraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPesquisaMontadoraMouseClicked
        produtoTableModel.setDados(pDAO.readMontadora(txtMontadora.getText()));
        aplicacaoTableModel.clear();
        lblImagem.setIcon(null);
        lblImagem.setText("Imagem");
    }//GEN-LAST:event_lblPesquisaMontadoraMouseClicked

    private void btnCarinhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarinhoActionPerformed
        TelaCarrinho carrinho = null;
        try {
            carrinho = new TelaCarrinho();
        } catch (FileNotFoundException ex) {
            System.out.println(ex);
        }
        carrinho.setVisible(true);
    }//GEN-LAST:event_btnCarinhoActionPerformed

    private void txtCodigoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodigoFocusGained
        if (txtCodigo.getText().isEmpty()) {
            txtCodigo.setText("Código Uniun ou referência");
        }
    }//GEN-LAST:event_txtCodigoFocusGained

    private void txtCodigoFocusGained2(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodigoFocusGained2
        if (txtCodigo.getText().equals("Código Uniun ou referência")) {
            txtCodigo.setText("");
        }
    }//GEN-LAST:event_txtCodigoFocusGained2

    private void txtCodigoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodigoFocusLost
        if (txtCodigo.getText().equals("")) {
            txtCodigo.setText("Código Uniun ou referência");
        }
    }//GEN-LAST:event_txtCodigoFocusLost

    private void txtMotorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMotorKeyPressed
        if (KeyEvent.VK_ENTER == evt.getKeyCode()) {
            produtoTableModel.setDados(pDAO.readMotorAplicacao(txtMotor.getText()));
            aplicacaoTableModel.clear();
            lblImagem.setIcon(null);
            lblImagem.setText("Imagem");
        }
    }//GEN-LAST:event_txtMotorKeyPressed

    private void lblPesquisaMotorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPesquisaMotorMouseClicked
        produtoTableModel.setDados(pDAO.readMotorAplicacao(txtMotor.getText()));
        aplicacaoTableModel.clear();
        lblImagem.setIcon(null);
        lblImagem.setText("Imagem");
    }//GEN-LAST:event_lblPesquisaMotorMouseClicked

    private void btnAddCarinhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCarinhoActionPerformed
        int selectedRow = jTabelaProdutos.getSelectedRow();
        String TableClick = (jTabelaProdutos.getModel().getValueAt(selectedRow, 0).toString());
        quantidade = JOptionPane.showInputDialog(this, "Insira uma quantidade");

        Produtosbean produto;
        produto = new Produtosbean();
        carrinhoDAO cDAO = null;
        try {
            cDAO = new carrinhoDAO();
        } catch (FileNotFoundException ex) {
            System.out.println(ex);
        }
        produto.setCodigo(Integer.parseInt(jTabelaProdutos.getModel().getValueAt(selectedRow, 0).toString()));

        produto.setQtd(Integer.parseInt(quantidade));
        JOptionPane.showMessageDialog(null, "Produto " +jTabelaProdutos.getModel().getValueAt(selectedRow, 3).toString()+ " adicionado ao carrinho");

        try {
            cDAO.create(produto);
        } catch (FileNotFoundException ex) {
            System.out.println(ex);
        }

//                          ~~ENVIAR PRO CARRINHO       
        if (enviarProduto == null) {
            try {
                enviarProduto = new TelaCarrinho();
            } catch (FileNotFoundException ex) {
                System.out.println(ex);
            }
            try {
                enviarProduto.recebeProduto(TableClick);
            } catch (FileNotFoundException ex) {
                System.out.println(ex);
            }
            if (enviarProduto.isVisible()) {
                enviarProduto.dispose();
            } else {
                enviarProduto.setVisible(true);
                enviarProduto.setState(TelaProdutos.NORMAL);
                try {
                    enviarProduto.recebeProduto(TableClick);
                } catch (FileNotFoundException ex) {
                    System.out.println("" + this + " " + ex);
                }
            }
        }
    }//GEN-LAST:event_btnAddCarinhoActionPerformed

    private void jTabelaProdutosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTabelaProdutosKeyReleased
        int selectedRow = jTabelaProdutos.getSelectedRow();
        if (evt.getKeyCode() == KeyEvent.VK_UP || evt.getKeyCode() == KeyEvent.VK_DOWN) {
            pDAO.readImage(jTabelaProdutos, lblImagem);
            aplicacaoTableModel.setDados(aDAO.search((int) jTabelaProdutos.getModel().getValueAt(selectedRow, 0)));
        }
    }//GEN-LAST:event_jTabelaProdutosKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new TelaProdutos().setVisible(true);
                } catch (SQLException ex) {
                    System.out.println(ex);
                }
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCarinho;
    private javax.swing.JButton btnCarinho;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTable jTabelaAplicação;
    private javax.swing.JTable jTabelaProdutos;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lblAbrirPesquisaAvançada;
    private javax.swing.JLabel lblFecharPesquisaAvançada;
    private javax.swing.JLabel lblHome;
    private javax.swing.JLabel lblImagem;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblPesquisaAplicacao;
    private javax.swing.JLabel lblPesquisaAvançada;
    private javax.swing.JLabel lblPesquisaCod;
    private javax.swing.JLabel lblPesquisaGeral;
    private javax.swing.JLabel lblPesquisaMontadora;
    private javax.swing.JLabel lblPesquisaMotor;
    private javax.swing.JLabel lblTipoPeca;
    private javax.swing.JLabel lbl_dispose;
    private javax.swing.JPanel paneLateral;
    private javax.swing.JPanel panePesquisaAvançada;
    private javax.swing.JTextField txtAplicacao;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtGambiarra;
    private javax.swing.JTextField txtMontadora;
    private javax.swing.JTextField txtMotor;
    private javax.swing.JTextField txtPesquisaGeral;
    private javax.swing.JTextField txtTipopeca;
    // End of variables declaration//GEN-END:variables
    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icone.png")));
    }
}
