package view;


import java.awt.Desktop;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.io.FileNotFoundException;
import java.net.URL;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UnsupportedLookAndFeelException;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author JOAOARTHURDELIMAFLORES
 */
public class TelaPesquisa extends javax.swing.JFrame {

    
    TelaProdutos enviarDados;

    /**
     * Creates new form TelaInicial
     * @throws javax.swing.UnsupportedLookAndFeelException
     */
    public TelaPesquisa() throws UnsupportedLookAndFeelException  {       
        initComponents();
        setIcon();
            
        panePesquisaAvançada.setVisible(false);         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        jPanel1 = new javax.swing.JPanel();
        TXTGAMBIARRA = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        lbl_dispose = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        txtPesquisaGeral = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        lblPesquisaAvançada = new javax.swing.JLabel();
        btnPesquisaGeral = new javax.swing.JLabel();
        panePesquisaAvançada = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        btnCodigo = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        btnMontadora = new javax.swing.JLabel();
        btnTipo = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtMontadora = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        txtTipo = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        btnLimparCampos = new javax.swing.JButton();
        btnCatalogoPDF = new javax.swing.JButton();
        btnCarrinho = new javax.swing.JButton();
        btnSite = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Catalogo Eletronico Uniun Juntas - HomePage");
        setMinimumSize(new java.awt.Dimension(800, 550));
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(32, 56, 100)));

        TXTGAMBIARRA.setBorder(null);

        jPanel2.setBackground(new java.awt.Color(32, 56, 100));

        lbl_dispose.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        lbl_dispose.setForeground(new java.awt.Color(255, 255, 255));
        lbl_dispose.setText("X");
        lbl_dispose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_disposeMouseClicked(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logo.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Catalogo Eletronico");

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_dispose)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_dispose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(32, 56, 100));
        jLabel3.setText("Pesquisa");

        txtPesquisaGeral.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txtPesquisaGeral.setForeground(new java.awt.Color(153, 153, 153));
        txtPesquisaGeral.setText("Pesquisa Geral (código, montadora, etc)");
        txtPesquisaGeral.setBorder(null);
        txtPesquisaGeral.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPesquisaGeralFocusGained(evt);
                txtPesquisaGeralFocusGained2(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPesquisaGeralFocusLost(evt);
            }
        });
        txtPesquisaGeral.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPesquisaGeralKeyPressed(evt);
            }
        });

        lblPesquisaAvançada.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        lblPesquisaAvançada.setForeground(new java.awt.Color(32, 56, 100));
        lblPesquisaAvançada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/+.png"))); // NOI18N
        lblPesquisaAvançada.setText("Pesquisa Avançada");
        lblPesquisaAvançada.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblPesquisaAvançada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                abreMenu(evt);
                fechaMenu(evt);
            }
        });

        btnPesquisaGeral.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/search.png"))); // NOI18N
        btnPesquisaGeral.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnPesquisaGeral.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPesquisaGeralMouseClicked(evt);
            }
        });

        panePesquisaAvançada.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(32, 56, 100));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Código");

        txtCodigo.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txtCodigo.setForeground(new java.awt.Color(153, 153, 153));
        txtCodigo.setText("ex: 11150112");
        txtCodigo.setBorder(null);
        txtCodigo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCodigoFocusGained(evt);
                txtCodigoFocusGained2(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCodigoFocusLost(evt);
            }
        });
        txtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCodigoKeyPressed(evt);
            }
        });

        btnCodigo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/search.png"))); // NOI18N
        btnCodigo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCodigo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCodigoMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(32, 56, 100));
        jLabel7.setText("Montadora");

        btnMontadora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/search.png"))); // NOI18N
        btnMontadora.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnMontadora.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMontadoraMouseClicked(evt);
            }
        });

        btnTipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/search.png"))); // NOI18N
        btnTipo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnTipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTipoMouseClicked(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(32, 56, 100));
        jLabel11.setText("Tipo");

        txtMontadora.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txtMontadora.setForeground(new java.awt.Color(153, 153, 153));
        txtMontadora.setText("ex: Peugeot");
        txtMontadora.setBorder(null);
        txtMontadora.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtMontadoraFocusGained(evt);
                txtMontadoraFocusGained2(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMontadoraFocusLost(evt);
            }
        });
        txtMontadora.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMontadoraKeyPressed(evt);
            }
        });

        txtTipo.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txtTipo.setForeground(new java.awt.Color(153, 153, 153));
        txtTipo.setText("ex: Junta de cabeçote");
        txtTipo.setBorder(null);
        txtTipo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTipoFocusGained(evt);
                txtTipoFocusGained2(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTipoFocusLost(evt);
            }
        });
        txtTipo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTipoKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout panePesquisaAvançadaLayout = new javax.swing.GroupLayout(panePesquisaAvançada);
        panePesquisaAvançada.setLayout(panePesquisaAvançadaLayout);
        panePesquisaAvançadaLayout.setHorizontalGroup(
            panePesquisaAvançadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panePesquisaAvançadaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panePesquisaAvançadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addGroup(panePesquisaAvançadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panePesquisaAvançadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panePesquisaAvançadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addGroup(panePesquisaAvançadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtMontadora)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panePesquisaAvançadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtTipo)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(panePesquisaAvançadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTipo)
                    .addComponent(btnMontadora)
                    .addComponent(btnCodigo))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        panePesquisaAvançadaLayout.setVerticalGroup(
            panePesquisaAvançadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panePesquisaAvançadaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panePesquisaAvançadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCodigo)
                    .addGroup(panePesquisaAvançadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 15, Short.MAX_VALUE)
                .addGroup(panePesquisaAvançadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnMontadora)
                    .addGroup(panePesquisaAvançadaLayout.createSequentialGroup()
                        .addGroup(panePesquisaAvançadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMontadora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, 0)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(7, 7, 7)
                .addGroup(panePesquisaAvançadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnTipo)
                    .addGroup(panePesquisaAvançadaLayout.createSequentialGroup()
                        .addGroup(panePesquisaAvançadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21))
        );

        btnLimparCampos.setBackground(new java.awt.Color(32, 56, 100));
        btnLimparCampos.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnLimparCampos.setForeground(new java.awt.Color(255, 255, 255));
        btnLimparCampos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/clear.png"))); // NOI18N
        btnLimparCampos.setText("     Limpar Campos                     ");
        btnLimparCampos.setBorder(null);
        btnLimparCampos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnLimparCampos.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btnLimparCampos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLimparCamposMouseClicked(evt);
            }
        });

        btnCatalogoPDF.setBackground(new java.awt.Color(32, 56, 100));
        btnCatalogoPDF.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnCatalogoPDF.setForeground(new java.awt.Color(255, 255, 255));
        btnCatalogoPDF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/pdf.png"))); // NOI18N
        btnCatalogoPDF.setText("     Catalogo em PDF                   ");
        btnCatalogoPDF.setBorder(null);
        btnCatalogoPDF.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCatalogoPDF.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btnCatalogoPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCatalogoPDFActionPerformed(evt);
            }
        });

        btnCarrinho.setBackground(new java.awt.Color(32, 56, 100));
        btnCarrinho.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnCarrinho.setForeground(new java.awt.Color(255, 255, 255));
        btnCarrinho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cart.png"))); // NOI18N
        btnCarrinho.setText("     Carrinho                                 ");
        btnCarrinho.setBorder(null);
        btnCarrinho.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCarrinho.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btnCarrinho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarrinhoActionPerformed(evt);
            }
        });

        btnSite.setBackground(new java.awt.Color(32, 56, 100));
        btnSite.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnSite.setForeground(new java.awt.Color(255, 255, 255));
        btnSite.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/website.png"))); // NOI18N
        btnSite.setText("     Website                                   ");
        btnSite.setBorder(null);
        btnSite.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnSite.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btnSite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiteActionPerformed(evt);
            }
        });

        jLabel12.setForeground(new java.awt.Color(32, 56, 100));
        jLabel12.setText("Copyright © 2020 – Shagas System & Uniun Juntas ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panePesquisaAvançada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPesquisaAvançada)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator2)
                            .addComponent(txtPesquisaGeral, javax.swing.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPesquisaGeral))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnSite, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnCatalogoPDF, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnLimparCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnCarrinho, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(358, 358, 358)
                        .addComponent(TXTGAMBIARRA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel12)))
                .addContainerGap(406, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(TXTGAMBIARRA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtPesquisaGeral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnPesquisaGeral))
                .addGap(0, 0, 0)
                .addComponent(lblPesquisaAvançada)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panePesquisaAvançada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimparCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCarrinho, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCatalogoPDF, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSite, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_disposeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_disposeMouseClicked
        this.dispose();
    }//GEN-LAST:event_lbl_disposeMouseClicked

    private void txtPesquisaGeralFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPesquisaGeralFocusLost
        if (txtPesquisaGeral.getText().equals("")){
            txtPesquisaGeral.setText("Pesquisa Geral (código, montadora, etc)");
    }
    }//GEN-LAST:event_txtPesquisaGeralFocusLost

    private void txtPesquisaGeralFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPesquisaGeralFocusGained
        if (txtPesquisaGeral.getText().isEmpty()) {
            txtPesquisaGeral.setText("Pesquisa Geral (código, montadora, etc)");
        }
    }//GEN-LAST:event_txtPesquisaGeralFocusGained

    private void txtCodigoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodigoFocusGained
        if (txtCodigo.getText().isEmpty()){
            txtCodigo.setText("ex: 11150112");
        }
    }//GEN-LAST:event_txtCodigoFocusGained

    private void txtCodigoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodigoFocusLost
        if (txtCodigo.getText().equals("")){
            txtCodigo.setText("ex: 11150112");
        }
    }//GEN-LAST:event_txtCodigoFocusLost

    private void abreMenu(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_abreMenu
        if (panePesquisaAvançada.isVisible()){
            panePesquisaAvançada.setVisible(false);
        } else{
            panePesquisaAvançada.setVisible(true);
        }
                        
    }//GEN-LAST:event_abreMenu

    private void txtCodigoFocusGained2(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodigoFocusGained2
        if (txtCodigo.getText().equals("ex: 11150112")){
            txtCodigo.setText("");
        }
    }//GEN-LAST:event_txtCodigoFocusGained2

    private void txtPesquisaGeralFocusGained2(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPesquisaGeralFocusGained2
        if (txtPesquisaGeral.getText().equals("Pesquisa Geral (código, montadora, etc)")){
            txtPesquisaGeral.setText("");
        }
    }//GEN-LAST:event_txtPesquisaGeralFocusGained2

    private void fechaMenu(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fechaMenu
        
    }//GEN-LAST:event_fechaMenu

    private void btnCarrinhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarrinhoActionPerformed
        TelaCarrinho carrinho = null;
        try {
            carrinho = new TelaCarrinho();
        } catch (FileNotFoundException ex) {
            System.out.println(ex);
        }
        carrinho.setVisible(true);
    }//GEN-LAST:event_btnCarrinhoActionPerformed

    private void btnLimparCamposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimparCamposMouseClicked
        txtPesquisaGeral.setText("");
        txtCodigo.setText("");
        txtMontadora.setText("");
        txtTipo.setText("");
    }//GEN-LAST:event_btnLimparCamposMouseClicked

    private void btnPesquisaGeralMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPesquisaGeralMouseClicked
        if(enviarDados == null){
            try {
                enviarDados = new TelaProdutos();
            } catch (SQLException ex) {
                
            }
            enviarDados.setVisible(true);
            enviarDados.recebePesquisaGeral(txtPesquisaGeral.getText());
            this.dispose();
        } else {
            enviarDados.setVisible(true);
            enviarDados.setState(TelaProdutos.NORMAL);
            enviarDados.recebePesquisaGeral(txtPesquisaGeral.getText());
        }
    }//GEN-LAST:event_btnPesquisaGeralMouseClicked

    private void btnCodigoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCodigoMouseClicked
        if(enviarDados == null){
            try {
                enviarDados = new TelaProdutos();
            } catch (SQLException ex) {
                System.out.println(ex);
            }
            enviarDados.setVisible(true);
            enviarDados.recebeCodigo(txtCodigo.getText());
            this.dispose();
        } else {
            enviarDados.setVisible(true);
            enviarDados.setState(TelaProdutos.NORMAL);
            enviarDados.recebeCodigo(txtCodigo.getText());
        }
    }//GEN-LAST:event_btnCodigoMouseClicked

    private void txtMontadoraFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMontadoraFocusGained
        if (txtMontadora.getText().isEmpty()){
            txtMontadora.setText("ex: Peugeot");
        }
    }//GEN-LAST:event_txtMontadoraFocusGained

    private void txtMontadoraFocusGained2(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMontadoraFocusGained2
        if (txtMontadora.getText().equals("ex: Peugeot")){
            txtMontadora.setText("");
        }
    }//GEN-LAST:event_txtMontadoraFocusGained2

    private void txtMontadoraFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMontadoraFocusLost
        if (txtMontadora.getText().equals("")){
            txtMontadora.setText("ex: Peugeot");
        }
    }//GEN-LAST:event_txtMontadoraFocusLost

    private void txtTipoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTipoFocusGained
        if (txtTipo.getText().isEmpty()){
            txtTipo.setText("ex: Junta de cabeçote");
        }
    }//GEN-LAST:event_txtTipoFocusGained

    private void txtTipoFocusGained2(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTipoFocusGained2
        if (txtTipo.getText().equals("ex: Junta de cabeçote")){
            txtTipo.setText("");
        }
    }//GEN-LAST:event_txtTipoFocusGained2

    private void txtTipoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTipoFocusLost
        if (txtTipo.getText().equals("")){
            txtTipo.setText("ex: Junta de cabeçote");
        }
    }//GEN-LAST:event_txtTipoFocusLost

    private void btnMontadoraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMontadoraMouseClicked
        if(enviarDados == null){
            try {
                enviarDados = new TelaProdutos();
            } catch (SQLException ex) {
                System.out.println(ex);
            }
            enviarDados.setVisible(true);
            enviarDados.recebeMontadora(txtMontadora.getText());
            this.dispose();
        } else {
            enviarDados.setVisible(true);
            enviarDados.setState(TelaProdutos.NORMAL);
            enviarDados.recebeMontadora(txtMontadora.getText());
        }
    }//GEN-LAST:event_btnMontadoraMouseClicked

    private void btnTipoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTipoMouseClicked
        if(enviarDados == null){
            try {
                enviarDados = new TelaProdutos();
            } catch (SQLException ex) {
                System.out.println(ex);
            }
            enviarDados.setVisible(true);
            enviarDados.recebeTipo(txtTipo.getText());
            this.dispose();
        } else {
            enviarDados.setVisible(true);
            enviarDados.setState(TelaProdutos.NORMAL);
            enviarDados.recebeTipo(txtTipo.getText());
        }
    }//GEN-LAST:event_btnTipoMouseClicked

    private void txtPesquisaGeralKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisaGeralKeyPressed
        if (KeyEvent.VK_ENTER == evt.getKeyCode()) {
        if(enviarDados == null){
            try {
                enviarDados = new TelaProdutos();
            } catch (SQLException ex) {
                System.out.println(ex);
            }
            enviarDados.setVisible(true);
            enviarDados.recebePesquisaGeral(txtPesquisaGeral.getText());
            this.dispose();
        } else {
            enviarDados.setVisible(true);
            enviarDados.setState(TelaProdutos.NORMAL);
            enviarDados.recebePesquisaGeral(txtPesquisaGeral.getText());
        }
        }
    }//GEN-LAST:event_txtPesquisaGeralKeyPressed

    private void txtCodigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoKeyPressed
        if (KeyEvent.VK_ENTER == evt.getKeyCode()){
            if(enviarDados == null){
            try {
                enviarDados = new TelaProdutos();
            } catch (SQLException ex) {
                System.out.println(ex);
            }
            enviarDados.setVisible(true);
            enviarDados.recebeCodigo(txtCodigo.getText());
            this.dispose();
        } else {
            enviarDados.setVisible(true);
            enviarDados.setState(TelaProdutos.NORMAL);
            enviarDados.recebeCodigo(txtCodigo.getText());
        }
        }
    }//GEN-LAST:event_txtCodigoKeyPressed

    private void txtMontadoraKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMontadoraKeyPressed
        if (KeyEvent.VK_ENTER == evt.getKeyCode()){
            if(enviarDados == null){
            try {
                enviarDados = new TelaProdutos();
            } catch (SQLException ex) {
                System.out.println(ex);
            }
            enviarDados.setVisible(true);
            enviarDados.recebeMontadora(txtMontadora.getText());
            this.dispose();
        } else {
            enviarDados.setVisible(true);
            enviarDados.setState(TelaProdutos.NORMAL);
            enviarDados.recebeMontadora(txtMontadora.getText());
        }
        }
    }//GEN-LAST:event_txtMontadoraKeyPressed

    private void txtTipoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTipoKeyPressed
        if (KeyEvent.VK_ENTER == evt.getKeyCode()){
            if(enviarDados == null){
            try {
                enviarDados = new TelaProdutos();
            } catch (SQLException ex) {
                System.out.println(ex);
            }
            enviarDados.setVisible(true);
            enviarDados.recebeTipo(txtTipo.getText());
            this.dispose();
        } else {
            enviarDados.setVisible(true);
            enviarDados.setState(TelaProdutos.NORMAL);
            enviarDados.recebeTipo(txtTipo.getText());
        }
        }
    }//GEN-LAST:event_txtTipoKeyPressed

    private void btnSiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiteActionPerformed
        try {
            Desktop.getDesktop().browse(new URL("http://www.uniunjuntas.com.br/").toURI());
        } catch (Exception e) {
            System.out.println("Erro ao abrir o site. "+e);
        }      
    }//GEN-LAST:event_btnSiteActionPerformed

    private void btnCatalogoPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCatalogoPDFActionPerformed
        try {
            Desktop.getDesktop().browse(new URL("http://www.uniunjuntas.com.br/Cat%C3%A1logo/").toURI());
        } catch (Exception e) {
            System.out.println("Erro ao abrir o site. "+e);
        } 
    }//GEN-LAST:event_btnCatalogoPDFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPesquisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPesquisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPesquisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPesquisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new TelaPesquisa().setVisible(true);
                } catch (UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(TelaPesquisa.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TXTGAMBIARRA;
    private javax.swing.JButton btnCarrinho;
    private javax.swing.JButton btnCatalogoPDF;
    private javax.swing.JLabel btnCodigo;
    private javax.swing.JButton btnLimparCampos;
    private javax.swing.JLabel btnMontadora;
    private javax.swing.JLabel btnPesquisaGeral;
    private javax.swing.JButton btnSite;
    private javax.swing.JLabel btnTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JLabel lblPesquisaAvançada;
    private javax.swing.JLabel lbl_dispose;
    private javax.swing.JPanel panePesquisaAvançada;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtMontadora;
    private javax.swing.JTextField txtPesquisaGeral;
    private javax.swing.JTextField txtTipo;
    // End of variables declaration//GEN-END:variables
    private void setIcon () {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icone.png")));
    }
}
